name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_TOKEN  }} 
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Cache Gradle Wrapper
      uses: actions/cache@v2
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

    - name: Cache Gradle Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-caches-
    - name: Make Gradlew Executable
      run: cd android && chmod +x ./gradlew  
    - name: installing npm
      run: npm i
      
    - name: Build with Gradle
      run: cd android && ./gradlew assembleRelease
      
    - name: finding apk path
      run: ls -la && cd android/app/build/outputs/apk/release/ && ls -la
    - name: upload apk
      uses: actions/upload-artifact@v3.1.0
      with: 
        name: extentiademoapp.apk
        path: android/app/build/outputs/apk/release/
        
    - name: App Center
      uses: wzieba/AppCenter-Github-Action@v1.3.3
      with: 
        appName: Athena-Dev/Athena-Android
        token: ${{ env.APP_CENTER_TOKEN }}
        group: Athena-Android
        file: android/app/build/outputs/apk/release/app-release.apk
        notifyTesters: true
        debug: false       
       
     
     
    
    
