name: IOS build

on: [workflow_dispatch]

jobs:
  build:
    name: IOS Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          
      - name: Install dependencies
        run: npm install --legacy-peer-deps
        
      - name: Install pod dependencies
        run: |
          cd ios && pod install 
      

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_13.2.1.app
        
      - name: Xcode Version
        run: /usr/bin/xcodebuild -version
        
      - name: Create build folder
        run: |
         mkdir -p build && mkdir -p staging 
        
      - name: Know permission
        run: cd ios && ls -la
        
      - name: change permission of file
        run: cd ios && sudo chmod +x decrypt_provision.sh
        
      - name: Know permission of a file
        run: cd ios && ls -la 
        
      - name: Decrypt large secret
        run: cd ios && ./decrypt_provision.sh    
      
      - name: find dycripted file
        run: cd ios/secrets && ls -la      
        
      #- name: Build IOS App
      #  uses: yukiarrr/ios-build-action@v1.4.0
      #  with:
      #    project-path: ios/ExtentiaDemoApp.xcodeproj
      #    p12-base64: ${{ secrets.IOS_P12_BASE64 }}
      #    mobileprovision-base64: ios/secrets/MYCEA_Development_Profile.mobileprovision
      #    team-id: ${{ secrets.IOS_TEAM_ID }}
      #    workspace-path: ios/ExtentiaDemoApp.xcworkspace
      #    scheme: ExtentiaDemoApp
     
      - name: Build Archive 
        run: |
           xcodebuild -workspace ios/ExtentiaDemoApp.xcworkspace \
                      -scheme ExtentiaDemoApp\ ios \
                      -sdk iphoneos \
                      -configuration AppStoreDistribution \
                      -archivePath ios/build/ExtentiaDemoApp.xcarchive \
                      clean archive | xcpretty
        
      
 
          
        
